name: 'bukkit-randomtp-plugin'
main: 'pl.rosehc.randomtp.RandomTPPlugin'
author: 'inzynierr'
depend: [ 'bukkit-adapter-plugin', 'bukkit-sectors-plugin', 'bukkit-platform-plugin', 'bukkit-actionbar-plugin' ]
softdepend: [ 'bukkit-guilds-plugin' ]
version: '1.0-SNAPSHOT'