name: 'bukkit-protection-plugin'
main: 'pl.rosehc.protection.ProtectionPlugin'
authors: [ 'stevimeister', 'inzynierr' ]
depend: [ 'bukkit-adapter-plugin', 'bukkit-sectors-plugin', 'bukkit-platform-plugin' ]
version: '1.0-SNAPSHOT'